package com.example

/**
 * Copyright eConsult Health Ltd 2022
 * Author : Jim Renwick
 * Date: 02/02/2022
 */
enum EventType {

    // events generated by user interactions with the frontend
    USER_SESSION_EVENT,
    // events generated to notify frontend of DB data that needs to be refreshed
    DATA_NOTIFICATION_EVENT

}